---

all:
  children:
    build:
      hosts:
        localhost:
          ansible_connection: local

    demo_hiv:
      hosts:
        demo:
          ansible_connection: local

    live_hiv:
      hosts:
        live:
          ansible_connection: local

    hivserver:
      children:
        demo_hiv:
        live_hiv:

