/*
 * Copyright (c) 2020 Web Essentials Co., Ltd
 */
export const ROUTES = {
  LOGIN: 'Login',
  HOME: 'Home',
  ACTIVITY: 'Activity',
  GOAL: 'Goal',
  APPOINTMENT: 'Appointment',
  MESSAGE: 'Message',
  USER_PROFILE: 'UserProfile',
  PRIVACY: 'Privacy',
  ABOUT: 'About',
  REGISTER: 'Register',
  TERM_OF_SERVICE: 'TermOfService',
  TERM_OF_SERVICE_DETAIL: 'TermOfServiceDetail',
  SETUP_PIN: 'SetupPin',
};

export const ACTIONS = {
  PATIENT_LOGIN_SUCCEED: 'PATIENT_LOGIN_SUCCEED',
  PATIENT_LOGIN_FAILED: 'PATIENT_LOGIN_FAILED',
  PATIENT_LOGOUT_SUCCEED: 'PATIENT_LOGOUT_SUCCEED',
  ACTIVITY_FETCH_SUCCEED: 'ACTIVITY_FETCH_SUCCEED',
  ACTIVITY_FETCH_FAILED: 'ACTIVITY_FETCH_FAILED',
  GOAL_FETCH_SUCCEED: 'GOAL_FETCH_SUCCEED',
  GOAL_FETCH_FAILED: 'GOAL_FETCH_FAILED',
  APPOINTMENT_FETCH_SUCCEED: 'APPOINTMENT_FETCH_SUCCEED',
  APPOINTMENT_FETCH_FAILED: 'APPOINTMENT_FETCH_FAILED',
  INDICATOR_UPDATE_SUCCEED: 'INDICATOR_UPDATE_SUCCEED',
};
