require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

# Firebase compatibility
use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true

target 'PatientApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebasePerformance', :modular_headers => true

  pod 'RNCallKeep', :path => '../node_modules/@webessentials/react-native-callkeep'
  pod 'react-native-twilio-video-webrtc', path: '../node_modules/@webessentials/react-native-twilio-video-webrtc'

  target 'PatientAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #post_install do |installer|
  #  flipper_post_install(installer)
  #end
end
