/*
 * Copyright (c) 2020 Web Essentials Co., Ltd
 */
export const ACTION_TYPE = {
  PATIENT_LOGIN_SUCCEED: 'PATIENT_LOGIN_SUCCEED',
  PATIENT_LOGIN_FAILED: 'PATIENT_LOGIN_FAILED',
  PATIENT_LOGOUT_SUCCEED: 'PATIENT_LOGOUT_SUCCEED',
  ACTIVITY_FETCH_SUCCEED: 'ACTIVITY_FETCH_SUCCEED',
  ACTIVITY_FETCH_FAILED: 'ACTIVITY_FETCH_FAILED',
  INDICATOR_UPDATE_SUCCEED: 'INDICATOR_UPDATE_SUCCEED',
};
