---

project_name:             'hiv'

git_repos:                'git@git.web-essentials.asia:hiv-tra-20/patient-app.git'

patient_api_base_url:     'https://demo-admin-rehabilitation.wehost.asia/api/patient'
admin_api_base_url:       'https://demo-admin-rehabilitation.wehost.asia/api/admin'
therapist_api_base_url:   'https://demo-admin-rehabilitation.wehost.asia/api/therapist'
rocketchat_base_url:      'https://demo-chat-rehabilitation.wehost.asia'
chat_websocket_url:       'wss://demo-chat-rehabilitation.wehost.asia/websocket'

is_debug_mode:            'false'

major_release_version:    '1'
minor_release_version:    '3'

android_build_path:       'android'
android_apk_file:         '{{ android_build_path }}/app/build/outputs/apk/release/app-release.apk'
andriod_sdk_path:         '{{ jenkin_home }}/Android/Sdk'

android_release_key_src:  '/opt/Android/{{ project_name }}/hiv-release-key.keystore'
android_release_path:     '/storage/satis/web/apk/{{ project_name }}'
android_apk_release_file: '{{ stage }}-{{ build_id }}-{{ ansible_date_time.date }}-app-release.apk'

store_pass:               '{{ store_pass_vault }}'
key_pass:                 '{{ key_pass_vault }}'
