---

- name: Run yarn to install node packages
  shell: yarn install
  args:
    chdir: '{{ workspace }}'

- name: Configure properties
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0755
  loop:
    - {src: 'settings.js.j2', dest: '{{ workspace }}/config/settings.js'}
    - {src: 'build.gradle.j2', dest: '{{ workspace }}/android/build.gradle'}
    - {src: 'local.properties.j2', dest: '{{ workspace }}/android/local.properties'}
    - {src: 'gradle.properties.j2', dest: '{{ workspace }}/{{ android_build_path }}/app/gradle.properties'}

- name: Configure Android release key
  copy:
    src: release-key.keystore.vault
    dest: '{{ workspace }}/{{ android_build_path }}/app/release-key.keystore'

- name: Build Android apk release app
  shell: 'JAVA_HOME=/usr/lib/jvm/java-10-openjdk-amd64 ./gradlew assembleRelease'
  args:
    chdir: '{{ workspace }}/{{ android_build_path }}'

- name: Copy release apk file to packages server
  shell: 'scp {{ android_apk_file }} dmz:{{ android_release_path }}/{{ android_apk_release_file }}'
  args:
    chdir: '{{ workspace }}'
